const DATA_URL="dashboard-data.json";
const zhMarket={h2h:"勝負",spreads:"讓球",totals:"大小球"};
const mlbLogo={ "Arizona Diamondbacks":"ari","Atlanta Braves":"atl","Baltimore Orioles":"bal","Boston Red Sox":"bos","Chicago Cubs":"chc","Chicago White Sox":"chw","Cincinnati Reds":"cin","Cleveland Guardians":"cle","Colorado Rockies":"col","Detroit Tigers":"det","Houston Astros":"hou","Kansas City Royals":"kc","Los Angeles Angels":"laa","Los Angeles Dodgers":"lad","Miami Marlins":"mia","Milwaukee Brewers":"mil","Minnesota Twins":"min","New York Mets":"nym","New York Yankees":"nyy","Athletics":"ath","Philadelphia Phillies":"phi","Pittsburgh Pirates":"pit","San Diego Padres":"sd","San Francisco Giants":"sf","Seattle Mariners":"sea","St. Louis Cardinals":"stl","Tampa Bay Rays":"tb","Texas Rangers":"tex","Toronto Blue Jays":"tor","Washington Nationals":"wsh" };
function tw(s){if(!s)return"";return new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(s))}
function state(x,football=false){if(football&&x.status==="SETTLED")return {WIN:"✅ 命中",HALF_WIN:"🟢 半贏",PUSH:"➖ 走盤",HALF_LOSS:"🟠 半輸",LOSS:"❌ 未命中"}[x.result]||"已結算";if(x.status==="WIN")return"✅ 命中";if(x.status==="LOSS")return"❌ 未命中";return"⏳ 未結算"}
function pickText(x,football=false){if(!football)return x.selection+" 勝";if(x.market==="totals")return(x.selection==="Under"?"小":"大")+" "+x.point;if(x.market==="spreads")return x.selection+" "+(Number(x.point)>0?"+":"")+x.point;return x.selection==="Draw"?"和局":x.selection+" 勝"}
function initials(n){return(n||"?").split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join("").toUpperCase()}
function badge(n,football=false){const code=!football&&mlbLogo[n];if(code)return `<span class="crest"><img src="https://a.espncdn.com/i/teamlogos/mlb/500/${code}.png" alt="" onerror="this.parentElement.textContent='${initials(n)}'"></span>`;return `<span class="crest" aria-hidden="true">${initials(n)}</span>`}
function reason(x,football=false){const edge=Number(x.edge_pct||0),p=Number(x.model_prob_pct||0);if(x.status==="OPEN")return `模型目前給推薦方 ${p}% 勝率，較市場高 ${edge.toFixed(1)} 個百分點；賽果尚未確定。`;if(!football&&x.postgame?.reasons?.length)return `<b>賽後分析：</b>${x.postgame.reasons.join(" ")}`;const good=football?["WIN","HALF_WIN"].includes(x.result):x.status==="WIN";const bad=football?["LOSS","HALF_LOSS"].includes(x.result):x.status==="LOSS";if(good)return `模型優勢有兌現：推薦方賽前估計 ${p}% ，市場差距 +${edge.toFixed(1)}%。`;if(bad)return `模型優勢未兌現：賽前雖估計 ${p}% 、市場差距 +${edge.toFixed(1)}%。`;if(football&&x.result==="PUSH")return "盤口最終走盤，這筆不列為命中或未命中。";return ""}
function cards(rows,football=false){return rows.map(x=>`<div class="match recommended"><div class="matchtime"><span class="result">${state(x,football)}</span>${tw(x.time)}</div><div class="teams"><span class="team">${badge(x.away,football)}<span>${x.away}</span></span><span class="versus">vs</span><span class="team">${badge(x.home,football)}<span>${x.home}</span></span></div><div class="choice"><span class="recommend-tag">推薦</span>${pickText(x,football)}</div><div class="meta"><span>${football?(zhMarket[x.market]||x.market):"勝負"}</span><span>模型 ${x.model_prob_pct}%</span><span>賠率 ${x.odds}</span><span>市場差距 +${x.edge_pct}%</span></div><div class="reason">${reason(x,football)}</div></div>`).join("")}
function sum(el,s,football=false){let html=`<div class="stat">目前預測<b>${s.predictions}</b></div><div class="stat">待結算<b>${s.open??(s.predictions-s.settled)}</b></div><div class="stat">已結算<b>${s.settled}</b></div>`;if(football){const r=s.results||{};html+=`<div class="stat">全贏<b>${r.WIN||0}</b></div><div class="stat">半贏 / 走盤<b>${r.HALF_WIN||0} / ${r.PUSH||0}</b></div><div class="stat">半輸 / 全輸<b>${r.HALF_LOSS||0} / ${r.LOSS||0}</b></div>`}else{html+=`<div class="stat">命中<b>${s.wins}</b></div><div class="stat">未命中<b>${s.losses}</b></div><div class="stat">命中率<b>${s.hit_rate_pct==null?"等待賽果":s.hit_rate_pct+"%"}</b></div>`}document.getElementById(el).innerHTML=html}
let dashboardData=null,historySport="mlb",historyStatus="all";
function renderHistory(){if(!dashboardData)return;let rows=dashboardData[historySport].history||[];if(historyStatus==="open")rows=rows.filter(x=>x.status==="OPEN");if(historyStatus==="settled")rows=rows.filter(x=>x.status!=="OPEN");document.getElementById("history-picks").innerHTML=rows.length?cards(rows,historySport==="football"):'<div class="muted">目前沒有符合條件的紀錄</div>'}
document.addEventListener("click",e=>{const b=e.target.closest("button.filter,button.status");if(!b)return;if(b.classList.contains("filter")){historySport=b.dataset.sport;document.querySelectorAll("button.filter").forEach(x=>x.classList.toggle("active",x===b))}else{historyStatus=b.dataset.status;document.querySelectorAll("button.status").forEach(x=>x.classList.toggle("active",x===b))}renderHistory()});
fetch(DATA_URL,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{dashboardData=d;sum("mlb-summary",d.mlb.summary);sum("football-summary",d.football.summary,true);document.getElementById("mlb-picks").innerHTML=cards(d.mlb.picks);document.getElementById("football-picks").innerHTML=cards(d.football.picks,true);renderHistory();document.getElementById("updated").textContent="資料更新："+tw(d.generated_at)}).catch(()=>{document.getElementById("updated").textContent="資料同步中，稍後自動重試"});
