const DATA_URL="dashboard-data.json";
const REFRESH_MS=60*1000;
const zhMarket={h2h:"勝負",spreads:"讓球",totals:"大小球"};
const eplLogo={ "Arsenal":"359","Aston Villa":"362","Bournemouth":"349","Brentford":"337","Brighton and Hove Albion":"397","Chelsea":"363","Coventry City":"388","Crystal Palace":"384","Everton":"368","Fulham":"370","Leeds United":"357","Liverpool":"364","Manchester City":"382","Manchester United":"360","Newcastle United":"361","Nottingham Forest":"393","Sunderland":"366","Tottenham Hotspur":"367" };
const mlbLogo={ "Arizona Diamondbacks":"ari","Atlanta Braves":"atl","Baltimore Orioles":"bal","Boston Red Sox":"bos","Chicago Cubs":"chc","Chicago White Sox":"chw","Cincinnati Reds":"cin","Cleveland Guardians":"cle","Colorado Rockies":"col","Detroit Tigers":"det","Houston Astros":"hou","Kansas City Royals":"kc","Los Angeles Angels":"laa","Los Angeles Dodgers":"lad","Miami Marlins":"mia","Milwaukee Brewers":"mil","Minnesota Twins":"min","New York Mets":"nym","New York Yankees":"nyy","Athletics":"ath","Philadelphia Phillies":"phi","Pittsburgh Pirates":"pit","San Diego Padres":"sd","San Francisco Giants":"sf","Seattle Mariners":"sea","St. Louis Cardinals":"stl","Tampa Bay Rays":"tb","Texas Rangers":"tex","Toronto Blue Jays":"tor","Washington Nationals":"wsh" };
function tw(s){if(!s)return"";return new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(s))}
function cardClass(x,football=false){if(football&&x.status==="SETTLED"){if(["WIN","HALF_WIN"].includes(x.result))return"win-card";if(["LOSS","HALF_LOSS"].includes(x.result))return"loss-card";return""}if(x.status==="OPEN")return"open-card";if(["WIN","WON"].includes(x.status))return"win-card";if(["LOSS","LOST"].includes(x.status))return"loss-card";return""}
function statusBadge(text,kind="building"){return '<span class="status-badge '+kind+'">'+text+'</span>'}
function state(x,football=false){if(football&&x.status==="SETTLED")return {WIN:"✅ 命中",HALF_WIN:"🟢 半贏",PUSH:"➖ 走盤",HALF_LOSS:"🟠 半輸",LOSS:"❌ 未命中"}[x.result]||"已結算";if(["WIN","WON"].includes(x.status))return"✅ 命中";if(["LOSS","LOST"].includes(x.status))return"❌ 未命中";if(["PUSH","VOID","CANCELLED"].includes(x.status))return"➖ 無輸贏";return"⏳ 未結算"}
function pickText(x,football=false){if(!football)return x.selection+" 勝";if(x.market==="totals")return(x.selection==="Under"?"小":"大")+" "+x.point;if(x.market==="spreads")return x.selection+" "+(Number(x.point)>0?"+":"")+x.point;return x.selection==="Draw"?"和局":x.selection+" 勝"}
function initials(n){return(n||"?").split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join("").toUpperCase()}
function badge(n,football=false){const code=football?eplLogo[n]:mlbLogo[n];if(code){const sport=football?"soccer":"mlb";return '<span class="crest"><img src="https://a.espncdn.com/i/teamlogos/'+sport+'/500/'+code+'.png" alt="'+n+' 隊徽" loading="lazy" onerror="this.parentElement.textContent=\''+initials(n)+'\'"></span>'}return '<span class="crest" aria-hidden="true">'+initials(n)+'</span>'}
function reason(x,football=false){const edge=Number(x.edge_pct||0),p=Number(x.model_prob_pct||0);if(x.status==="OPEN")return "";if(!football&&x.postgame?.reasons?.length)return `<b>賽後分析：</b>${x.postgame.reasons.join(" ")}`;const good=football?["WIN","HALF_WIN"].includes(x.result):x.status==="WIN";const bad=football?["LOSS","HALF_LOSS"].includes(x.result):x.status==="LOSS";if(good)return `模型優勢有兌現：推薦方賽前估計 ${p}% ，市場差距 +${edge.toFixed(1)}%。`;if(bad)return `模型優勢未兌現：賽前雖估計 ${p}% 、市場差距 +${edge.toFixed(1)}%。`;if(football&&x.result==="PUSH")return "盤口最終走盤，這筆不列為命中或未命中。";return ""}
function cards(rows,football=false){
 if(!football)return rows.map(x=>`<div class="match recommended ${cardClass(x,false)}"><div class="matchtime"><span class="result">${state(x,false)}</span>${tw(x.time)}</div><div class="teams"><span class="team">${badge(x.away,false)}<span>${x.away}</span></span><span class="versus">vs</span><span class="team">${badge(x.home,false)}<span>${x.home}</span></span></div><div class="choice"><span class="recommend-tag">推薦</span>${pickText(x,false)}</div><div class="meta"><span>勝負</span><span>模型 ${x.model_prob_pct}%</span><span>賠率 ${x.odds}</span><span>市場差距 +${x.edge_pct}%</span></div>${reason(x,false)?`<div class="reason">${reason(x,false)}</div>`:""}</div>`).join("");
 const groups=new Map();
 rows.forEach(x=>{const k=[x.time,x.home,x.away].join("|");if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)});
 return [...groups.values()].map(g=>{const x=g[0];const allSettled=g.every(r=>r.status==="SETTLED");return `<div class="match recommended ${allSettled?"settled-card":"open-card"}"><div class="matchtime"><span class="result">${allSettled?"✅ 已結算":"⏳ 未結算"}</span>${tw(x.time)}</div><div class="teams"><span class="team">${badge(x.away,true)}<span>${x.away}</span></span><span class="versus">vs</span><span class="team">${badge(x.home,true)}<span>${x.home}</span></span></div><div class="recommendations">${g.map(r=>`<div class="recommendation-row"><div class="choice"><span class="recommend-tag">推薦</span>${pickText(r,true)} <span class="result">${state(r,true)}</span></div><div class="meta"><span>${zhMarket[r.market]||r.market}</span><span>模型 ${r.model_prob_pct}%</span><span>賠率 ${r.odds}</span><span>市場差距 +${r.edge_pct}%</span></div>${reason(r,true)?`<div class="reason">${reason(r,true)}</div>`:""}</div>`).join("")}</div></div>`}).join("")
}
function healthCard(name,h){if(!h)return "";const v=h.validation||{};const kind=(h.status||"").match(/ready|stable|validated|完成|可用/i)?"ready":"building";return `<div class="healthbox" data-state="${kind}"><b>${name} ${statusBadge(h.status||"等待資料",kind)}</b><div class="healthbar"><i style="width:${h.progress_pct||0}%"></i></div><div class="healthmeta">已結算 ${h.settled} / ${h.review_at} 筆｜進度 ${h.progress_pct||0}%${v.brier!=null?`<br>歷史驗證 Brier ${v.brier}｜Log Loss ${v.log_loss}`:""}<br>${h.note||""}</div></div>`}
function footballHealthCards(h){if(!h)return "";const leagues=[["E0","英超"],["SP1","西甲"],["F1","法甲"],["I1","義甲"],["D1","德甲"],["USA","美國職足"],["BRA","巴西甲"],["N1","荷甲"],["P1","葡超"],["SC0","蘇超"]];const by=h.validation?.by_league||{};return leagues.map(([code,name])=>{const v=by[code]||{};const settled=n0(h.settled_by_league?.[code]);return healthCard("⚽ "+name,{...h,settled,progress_pct:Math.min(100,settled),note:(h.note||""),validation:{brier:n0(v.brier),log_loss:n0(v.log_loss),n:n0(v.n),folds:n0(v.folds)}})}).join("")}
function renderHealth(d){const h=d.model_health||{};let mlb=healthCard("⚾ 美職",h.mlb);const fc=h.mlb?.forward_calibration;if(fc){const buckets=(fc.buckets||[]).map(x=>`${x.range}: ${x.actual_win_pct}% / 模型 ${x.avg_model_prob_pct}% (n=${x.n})`).join("<br>");const edges=(fc.edge_buckets||[]).map(x=>`${x.range}: ${x.wins}勝 ${x.losses}敗｜命中 ${x.hit_rate_pct}%｜ROI ${x.roi_pct==null?"—":x.roi_pct+"%"}｜n=${x.n}`).join("<br>");mlb+=`<div class="healthbox"><b>⚾ MLB Forward Calibration ${statusBadge(fc.n>=100?"可檢視":"累積樣本中",fc.n>=100?"ready":"building")}</b><div class="healthmeta">已結算 n=${fc.n} / ${fc.review_at||100}｜Brier ${fc.brier??"—"}｜Log Loss ${fc.log_loss??"—"}｜校準差 ${fc.calibration_gap_pct==null?"—":fc.calibration_gap_pct+"%"}${buckets?`<br><br><b>機率校準</b><br>${buckets}`:""}${edges?`<br><br><b>Edge 分層</b><br>${edges}`:""}</div></div>`}const asia=h.asia_baseball||{};for(const [k,name] of [["NPB","🇯🇵 日職"],["KBO","🇰🇷 韓職"]]){const x=asia[k];if(!x)continue;const fc=x.forward_calibration||{};const buckets=(fc.buckets||[]).map(b=>`${b.range}: 實際 ${b.actual_win_pct}% / 模型 ${b.avg_model_prob_pct}% (n=${b.n})`).join("<br>");mlb+=`<div class="healthbox"><b>${name}｜獨立模型驗證 ${statusBadge(fc.n>=100?"可檢視":"累積樣本中",fc.n>=100?"ready":"building")}</b><div class="healthmeta">歷史 Walk-forward n=${x.validation_n??"—"}｜Brier ${x.brier??"—"}｜Log Loss ${x.log_loss??"—"}｜Accuracy ${x.accuracy_pct==null?"—":x.accuracy_pct+"%"}<br>Forward 已結算 ${fc.n||0} / ${fc.review_at||100}｜Brier ${fc.brier??"—"}｜Log Loss ${fc.log_loss??"—"}｜校準差 ${fc.calibration_gap_pct==null?"—":fc.calibration_gap_pct+"%"}${buckets?`<br><br><b>Forward 機率校準</b><br>${buckets}`:""}</div></div>`}document.getElementById("model-health").innerHTML=mlb+footballHealthCards(h.football)||'<div class="muted">尚無模型健康資料</div>'}
function n0(v){const n=Number(v);return Number.isFinite(n)?n:0}
function sum(el,s,football=false){if(!document.getElementById(el))return;let html=football?`<div class="stat">今日賽事<b>${n0(s.games_today)}</b></div><div class="stat">今日推薦<b>${n0(s.today_recommendations)}</b></div><div class="stat">未來推薦<b>${n0(s.future_recommendations)}</b></div><div class="stat">最新模型預測<b>${n0(s.model_predictions)}</b></div><div class="stat">今日待結算<b>${n0(s.today_open)}</b></div><div class="stat">今日已結算<b>${n0(s.settled_today)}</b></div>`:`<div class="stat">今日賽事<b>${n0(s.predictions)}</b></div><div class="stat">待結算<b>${s.open??(s.predictions-s.settled)}</b></div><div class="stat">已結算<b>${s.settled}</b></div>`;if(football){const r=s.results||{};html+=`<div class="stat">全贏<b>${r.WIN||0}</b></div><div class="stat">半贏 / 走盤<b>${r.HALF_WIN||0} / ${r.PUSH||0}</b></div><div class="stat">半輸 / 全輸<b>${r.HALF_LOSS||0} / ${r.LOSS||0}</b></div>`}else{html+=`<div class="stat">命中<b>${s.wins}</b></div><div class="stat">未命中<b>${s.losses}</b></div><div class="stat">命中率<b>${s.hit_rate_pct==null?"等待賽果":s.hit_rate_pct+"%"}</b></div>`}document.getElementById(el).innerHTML=html}
let dashboardData=null,historySport="mlb",historyStatus="all";
function renderHistory(){if(!dashboardData)return;let rows=dashboardData[historySport].history||[];if(historyStatus==="open")rows=rows.filter(x=>x.status==="OPEN");if(historyStatus==="settled")rows=rows.filter(x=>x.status!=="OPEN");document.getElementById("history-picks").innerHTML=rows.length?cards(rows,historySport==="football"):'<div class="muted">目前沒有符合條件的紀錄</div>'}
document.addEventListener("click",e=>{const b=e.target.closest("button.filter,button.status");if(!b)return;if(b.classList.contains("filter")){historySport=b.dataset.sport;document.querySelectorAll("button.filter").forEach(x=>x.classList.toggle("active",x===b))}else{historyStatus=b.dataset.status;document.querySelectorAll("button.status").forEach(x=>x.classList.toggle("active",x===b))}renderHistory()});
function copyInto(src,dst){const a=document.getElementById(src),b=document.getElementById(dst);if(a&&b)b.innerHTML=a.innerHTML}
function renderTodayCenter(d){const box=document.getElementById("today-center");if(!box)return;const rows=[];const add=(time,sport,label,match,pick=false)=>{if(time)rows.push({time,sport,label,match,pick})};(d.mlb?.picks||[]).filter(x=>x.status==="OPEN").forEach(x=>add(x.time,"⚾ 美職","美職",x.away+" vs "+x.home,true));const a=d.asia_baseball||{};["npb","kbo"].forEach(k=>(a[k]?.picks||[]).filter(x=>x.status==="OPEN").forEach(x=>add(x.time||x.commence_time,k==="npb"?"🇯🇵 日職":"🇰🇷 韓職",k.toUpperCase(),(x.away||x.away_team||"")+" vs "+(x.home||x.home_team||""),true)));const fp=new Set((d.football?.picks||[]).filter(x=>x.status==="OPEN").map(x=>[x.time,x.away,x.home].join("|")));(d.football_leagues?.leagues||[]).forEach(l=>(l.games||[]).forEach(g=>add(g.commence_time,"⚽ "+l.name,l.name,g.away_team+" vs "+g.home_team,fp.has([g.commence_time,g.away_team,g.home_team].join("|")))));rows.sort((a,b)=>new Date(a.time)-new Date(b.time));box.innerHTML=rows.length?rows.slice(0,30).map(r=>'<div class="today-row '+(r.pick?"has-pick":"")+'"><b>'+tw(r.time).split(" ")[1]+'</b><span>'+r.sport+'</span><span>'+r.match+'</span><span class="tag '+(r.pick?"picktag":"")+'">'+(r.pick?"有推薦":"賽程")+'</span></div>').join(""):'<div class="empty">目前沒有今日賽程或待觀察項目</div>'}
function renderFootballLeagues(d){const box=document.getElementById("football-leagues");if(!box)return;const x=d.football_leagues||{},ls=x.leagues||[];const chips=ls.map(l=>`<div class="leaguechip ${l.stage==="paper_model"?"model":""}"><span class="stage ${l.stage==="paper_model"?"ready":""}">${l.stage_label||"資料收集中"}</span><b>${l.name}｜${l.game_count||0} 場</b></div>`).join("");const games=ls.flatMap(l=>(l.games||[]).map(g=>({...g,league:l.name}))).sort((a,b)=>String(a.commence_time).localeCompare(String(b.commence_time)));const schedule=games.length?games.map(g=>`<div class="schedule-row"><b>${tw(g.commence_time).split(" ")[1]||tw(g.commence_time)}</b><span>${g.league}</span><span>${g.away_team} <span class="muted">vs</span> ${g.home_team}</span></div>`).join(""):'<div class="muted">指定日期目前沒有賽事</div>';box.innerHTML=`<div class="healthmeta">台灣日期 ${x.date_taipei||"—"}｜共 ${x.total_games||0} 場｜已有模型 ${x.validated_models||0} / ${x.configured_leagues||10} 聯賽</div><div class="league-filter"><button class="pill leaguepick active" data-league="all">全部</button>${ls.map(l=>`<button class="pill leaguepick" data-league="${l.name}">${l.name} ${l.game_count||0}</button>`).join("")}</div><div class="leaguechips">${chips}</div><div class="schedule-list">${schedule}</div>`}
function genericPickCards(rows,label){const leagueNames={E0:"英超",SP1:"西甲",F1:"法甲",I1:"義甲",D1:"德甲",USA:"美國職足",BRA:"巴西甲",N1:"荷甲",P1:"葡超",SC0:"蘇超"};return rows.map(x=>{const away=x.away||x.away_team||"—",home=x.home||x.home_team||"—",time=x.time||x.commence_time,sel=x.selection||x.pick||"觀察",league=leagueNames[x.division]||"";return '<div class="match recommended open-card"><div class="matchtime"><span class="result">'+statusBadge("待結算","open")+'</span>'+tw(time)+'</div><div class="teams"><span class="team"><span class="crest">'+initials(away)+'</span><span>'+away+'</span></span><span class="versus">vs</span><span class="team"><span class="crest">'+initials(home)+'</span><span>'+home+'</span></span></div><div class="choice"><span class="recommend-tag">'+label+(league?"｜"+league:"")+'</span>'+sel+'</div><div class="meta">'+(x.market?'<span>'+(zhMarket[x.market]||x.market)+'</span>':'')+(x.odds?'<span>賠率 '+x.odds+'</span>':'')+(x.edge_pct!=null?'<span>Edge +'+x.edge_pct+'%</span>':'')+'</div></div>'}).join("")}
function renderAsia(d){const box=document.getElementById("asia-baseball");if(!box)return;const a=d.asia_baseball||{};box.innerHTML=["npb","kbo"].map(k=>{const x=a[k]||{},s=x.summary||{},p=(x.picks||[]).filter(r=>r.status==="OPEN");return `<div class="healthbox" data-state="${(x.status||"").match(/ready|完成|可用/i)?"ready":"building"}"><b>${k==="npb"?"🇯🇵 日職":"🇰🇷 韓職"} ${statusBadge(x.status||"等待資料",(x.status||"").match(/ready|完成|可用/i)?"ready":"building")}</b><div class="healthmeta">模型 ${x.model||"尚未選定"}｜推薦 ${s.total_bets||0} 筆｜待結算 ${s.open||0}｜已結算 ${s.settled||0}<br>戰績 ${s.wins||0} 勝 / ${s.losses||0} 敗｜PnL ${s.pnl_units==null?"—":Number(s.pnl_units).toFixed(2)}u｜ROI ${s.roi==null?"—":(100*Number(s.roi)).toFixed(1)+"%"}</div><div class="matchcards" style="grid-template-columns:1fr;margin-top:10px">${p.length?genericPickCards(p,"推薦"):`<div class="empty">目前沒有待結算推薦</div>`}</div></div>`}).join("")}
function render美足(d){const box=document.getElementById("nfl-status");if(!box)return;const x=d.nfl||{},p=(x.picks||[]).filter(r=>r.status==="OPEN");box.innerHTML=`<div class="grid"><div class="healthbox"><b>🏈 美足｜${x.status||"等待資料"}</b><div class="healthmeta">市場：勝負、大小分｜近期賽事 ${x.events||0} 場｜盤口 ${x.snapshot_rows||0} 筆<br>每 15 分鐘檢查｜開賽前約 30 分鐘抓取盤口｜剩餘 API 額度 ${x.remaining_credits??"—"}</div></div><div class="healthbox"><b>模型狀態｜${x.model_status||"尚未建立"}</b><div class="healthmeta">${x.note||"只顯示資料狀態，不產生未驗證推薦。"}</div></div></div><div class="section-title"><h2>美足 待觀察</h2></div><div class="matchcards">${p.length?genericPickCards(p,"推薦"):'<div class="empty">目前沒有已驗證的 美足 推薦</div>'}</div>`}
document.addEventListener("click",e=>{const lf=e.target.closest(".leaguepick");if(lf){document.querySelectorAll(".leaguepick").forEach(x=>x.classList.toggle("active",x===lf));const want=lf.dataset.league;document.querySelectorAll("#football-leagues .schedule-row").forEach(r=>r.classList.toggle("hidden",want!=="all"&&r.children[1]?.textContent!==want));return}const b=e.target.closest(".navbtn");if(!b)return;document.querySelectorAll(".navbtn").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+b.dataset.view));window.scrollTo({top:0,behavior:"smooth"})});
function renderCollectionHealth(d){
 const box=document.getElementById("collection-health");if(!box)return;
 const h=d.collection_health;
 if(!h){box.innerHTML='<div class="empty">等待後端產生採集健康資料</div>';return}
 const names={mlb:"⚾ MLB",npb:"🇯🇵 NPB",kbo:"🇰🇷 KBO",nfl:"🏈 NFL",football:"⚽ 足球"};
 const sports=h.sports||{};
 const status=(x)=>n0(x.missed)>0?"🔴":n0(x.pending)>0?"🟡":"🟢";
 const fmtT=(v)=>v==null?"—":"T-"+Math.abs(Number(v)).toFixed(1);
 const cardsHtml=Object.entries(names).map(([k,name])=>{const x=sports[k]||{};return `<div class="healthbox"><b>${status(x)} ${name}</b><div class="healthmeta">今日應抓 ${n0(x.expected_today)}｜已抓 ${n0(x.collected)}｜尚未到時間 ${n0(x.pending)}｜錯過視窗 ${n0(x.missed)}<br>抓取完成率 ${x.success_pct==null?"—":x.success_pct+"%"}｜實際抓取時間平均 ${fmtT(x.actual_t_minutes_avg)}｜範圍 ${x.actual_t_minutes_min==null?"—":fmtT(x.actual_t_minutes_min)+" ～ "+fmtT(x.actual_t_minutes_max)}</div></div>`}).join("");
 const overall=n0(h.missed)>0?"🔴 有錯過抓取視窗":n0(h.pending)>0?"🟡 等待賽前抓取":"🟢 正常";
 const issues=(h.issues||[]);const issueHtml=issues.length?`<div class="section-gap"><b>⚠️ 賽前盤口抓取異常</b><div class="schedule-list">${issues.slice(0,12).map(x=>`<div class="schedule-row"><b>${({mlb:"MLB",npb:"NPB",kbo:"KBO",nfl:"NFL",football:"足球"})[x.sport]||x.sport}</b><span>${tw(x.commence_time)}</span><span>${x.reason}</span></div>`).join("")}</div></div>`:"";box.innerHTML=`<div class="stats"><div class="stat">狀態<b>${overall}</b></div><div class="stat">今日應抓<b>${n0(h.expected_today)}</b></div><div class="stat">已抓<b>${n0(h.collected)}</b></div><div class="stat">尚未到時間<b>${n0(h.pending)}</b></div><div class="stat">錯過視窗<b>${n0(h.missed)}</b></div><div class="stat">抓取完成率<b>${h.success_pct==null?"—":h.success_pct+"%"}</b></div></div><div class="healthmeta" style="margin-top:10px">抓取時點：開賽前約 30 分鐘（允許開賽前 40～20 分鐘）｜最近 API calls ${n0(h.latest_run_paid_api_calls)}｜剩餘額度 ${h.remaining_credits??"—"}</div><div class="grid section-gap">${cardsHtml}</div>${issueHtml}`;
}
function syncHealth(d){
 const el=document.getElementById("sync-health");if(!el)return;
 const t=new Date(d.generated_at);const age=(Date.now()-t.getTime())/60000;
 const ch=d.collection_health||{};
 let state="🟢",label="正常";
 if(!Number.isFinite(age)){state="🔴";label="無更新時間"}
 else if(age>30){state="🔴";label="資料逾時"}
 else if(age>18){state="🟡";label="同步偏慢"}
 const missed=Number(ch.missed||0);
 if(missed>0&&state==="🟢"){state="🟡";label="有漏抓場次"}
 const sh=d.sync_health||{};const sourceLag=Number(sh.source_to_payload_lag_seconds);const frontendLag=Number.isFinite(age)?Math.max(0,Math.round(age*60)):null;if(Number.isFinite(sourceLag)&&sourceLag>300){state="🔴";label="後端→JSON 延遲"}else if(Number.isFinite(sourceLag)&&sourceLag>120&&state==="🟢"){state="🟡";label="後端→JSON 偏慢"}else if(frontendLag!=null&&frontendLag>300){state="🔴";label="JSON→前端 延遲"};el.textContent=`同步狀態：${state} ${label}｜後端→JSON ${Number.isFinite(sourceLag)?sourceLag+"秒":"—"}｜JSON→前端 ${frontendLag==null?"—":frontendLag+"秒"}${ch.success_pct!=null?"｜T-30 "+ch.success_pct+"%":""}${missed?"｜漏抓 "+missed+" 場":""}`;
}
function loadDashboard(){
  return fetch(DATA_URL+"?t="+Date.now(),{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{syncHealth(d);renderCollectionHealth(d);renderHealth(d);renderFootballLeagues(d);renderAsia(d);render美足(d);renderTodayCenter(d);dashboardData=d;sum("mlb-summary",d.mlb.summary);sum("mlb-summary-detail",d.mlb.summary);sum("football-summary",d.football.summary,true);const mlbWatch=(d.mlb.picks||[]).filter(x=>x.status==="OPEN");const footballWatch=(d.football.picks||[]).filter(x=>x.status==="OPEN");const empty='<div class="empty">目前沒有待觀察賽事</div>';document.getElementById("mlb-picks").innerHTML=mlbWatch.length?cards(mlbWatch):empty;document.getElementById("football-picks").innerHTML=footballWatch.length?cards(footballWatch,true):empty;copyInto("mlb-picks","mlb-picks-detail");copyInto("football-picks","football-picks-detail");renderHistory();document.getElementById("updated").textContent="資料更新："+tw(d.generated_at)}).catch(()=>{document.getElementById("updated").textContent="資料同步中，稍後自動重試"})
}
loadDashboard();
setInterval(loadDashboard,REFRESH_MS);
document.addEventListener("visibilitychange",()=>{if(!document.hidden)loadDashboard()});